//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMDump
    {
        public long ID { get; set; }
        public string SalesOrderTitle { get; set; }
        public Nullable<System.DateTime> DespatchDate { get; set; }
        public Nullable<System.DateTime> CusReqDate { get; set; }
        public string RunID { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string MainPart { get; set; }
        public string MainPartDescription { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string ParentMethod { get; set; }
        public string ParentVersion { get; set; }
        public string ParentIssue { get; set; }
        public string ParentResponsibility { get; set; }
        public string ComponentPart { get; set; }
        public string ComponentPartDescription { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<int> Level { get; set; }
        public string ComponentMethod { get; set; }
        public string ComponentVersion { get; set; }
        public string ComponentIssue { get; set; }
        public string ComponentUOM { get; set; }
        public Nullable<decimal> ScrapPercent { get; set; }
        public Nullable<decimal> SetQuantity { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> OverallQuantity { get; set; }
        public string DefaultLocation { get; set; }
        public string ProductGroup { get; set; }
        public string Responsibility { get; set; }
        public string ConsolidationWindow { get; set; }
        public Nullable<decimal> OnHandStockLevel { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
    }
}
