//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMLineShortage
    {
        public int ID { get; set; }
        public string SalesOrderTitle { get; set; }
        public Nullable<System.DateTime> DespatchDate { get; set; }
        public Nullable<System.DateTime> CustReqDate { get; set; }
        public string MainPart { get; set; }
        public string MainPartDescription { get; set; }
        public string ComponentPart { get; set; }
        public string ComponentPartDescription { get; set; }
        public string ComponentMethod { get; set; }
        public string ProductGroup { get; set; }
        public string Responsibility { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TotalBOMQuantity { get; set; }
        public Nullable<decimal> PriorDemand { get; set; }
        public Nullable<decimal> TotalDemand { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> WoQuantity { get; set; }
        public Nullable<decimal> WoOnTime { get; set; }
        public Nullable<System.DateTime> WoArriving { get; set; }
        public string WoDelayInDays { get; set; }
        public Nullable<decimal> PoQuantity { get; set; }
        public Nullable<decimal> PoOnTime { get; set; }
        public Nullable<System.DateTime> PoArriving { get; set; }
        public string PoDelayInDays { get; set; }
        public Nullable<decimal> Shortage { get; set; }
        public Nullable<decimal> OnTime { get; set; }
        public string ResourceCode { get; set; }
        public string ResourceGroupName { get; set; }
        public string ResourceType { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> WOIssued { get; set; }
    }
}
