//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMShortagesSupplierBreakdownSO
    {
        public int ID { get; set; }
        public string SalesOrderTitle { get; set; }
        public Nullable<System.DateTime> DespatchDate { get; set; }
        public string ComponentPart { get; set; }
        public string ComponentPartDescription { get; set; }
        public string ComponentMethod { get; set; }
        public string ProductGroup { get; set; }
        public string Responsibility { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public string SupplierName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> PriorDemand { get; set; }
        public Nullable<decimal> TotalDemand { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> WoQuantity { get; set; }
        public Nullable<decimal> WoOnTime { get; set; }
        public Nullable<decimal> PoQuantity { get; set; }
        public Nullable<decimal> PoOnTime { get; set; }
        public Nullable<decimal> Shortage { get; set; }
        public Nullable<decimal> OnTime { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<System.DateTime> POArriving { get; set; }
        public string PODelayInDays { get; set; }
        public Nullable<decimal> WOIssued { get; set; }
    }
}
