//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPSSUPBuyerShortageMetric
    {
        public int BuyerMetricID { get; set; }
        public string BuyerName { get; set; }
        public int SupplierCount { get; set; }
        public int ShortageCount { get; set; }
        public int NotOnOrder { get; set; }
        public int NotSupportingPODD { get; set; }
        public System.DateTime RecordingDate { get; set; }
        public decimal NotOnOrderQty { get; set; }
        public decimal NotSupportingPODDQty { get; set; }
        public int UniquePartsNotOnOrder { get; set; }
        public int UniquePartsNotSupportingPODD { get; set; }
    }
}
