//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOMExcelGenerator.OpenWorksOrderExcelGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReportDbEntities : DbContext
    {
        public ReportDbEntities()
            : base("name=ReportDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOMDump> BOMDumps { get; set; }
        public virtual DbSet<BOMLineShortage> BOMLineShortages { get; set; }
        public virtual DbSet<BOMShortageOwner> BOMShortageOwners { get; set; }
        public virtual DbSet<BOMShortageProductGroup> BOMShortageProductGroups { get; set; }
        public virtual DbSet<BOMShortagesSupplierBreakdown> BOMShortagesSupplierBreakdowns { get; set; }
        public virtual DbSet<BOMShortagesSupplierBreakdownSO> BOMShortagesSupplierBreakdownSOes { get; set; }
        public virtual DbSet<BOMSupplierManageMatrix> BOMSupplierManageMatrices { get; set; }
        public virtual DbSet<OPSSUPBuyerShortageMetric> OPSSUPBuyerShortageMetrics { get; set; }
    
        public virtual ObjectResult<ConnectShortageReport_Result> ConnectShortageReport(string so)
        {
            var soParameter = so != null ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConnectShortageReport_Result>("ConnectShortageReport", soParameter);
        }
    
        public virtual int ConnectShortageTotalsBuilder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConnectShortageTotalsBuilder");
        }
    
        public virtual int ConnectShortageReportFULL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConnectShortageReportFULL");
        }
    
        public virtual int ConnectShortageReportINDIVID(string so)
        {
            var soParameter = so != null ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConnectShortageReportINDIVID", soParameter);
        }
    
        public virtual int GetShortagesByPartDateSupplierINSERT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetShortagesByPartDateSupplierINSERT");
        }
    
        public virtual int GetShortagesByPartDateSupplierSOINSERT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetShortagesByPartDateSupplierSOINSERT");
        }
    }
}
