//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomExcelGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class thas01Entities : DbContext
    {
        public thas01Entities()
            : base("name=thas01Entities")
        {
            this.Database.CommandTimeout = 72000;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
    
        public virtual int THAS_CONNECT_BOMCYCLE(string salesOrderTitleName)
        {
            var salesOrderTitleNameParameter = salesOrderTitleName != null ?
                new ObjectParameter("SalesOrderTitleName", salesOrderTitleName) :
                new ObjectParameter("SalesOrderTitleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THAS_CONNECT_BOMCYCLE", salesOrderTitleNameParameter);
        }
    
        public virtual ObjectResult<string> THAS_CONNECT_GetShortageReportSOSchedule(Nullable<System.DateTime> periodstart, Nullable<System.DateTime> periodend)
        {
            var periodstartParameter = periodstart.HasValue ?
                new ObjectParameter("Periodstart", periodstart) :
                new ObjectParameter("Periodstart", typeof(System.DateTime));
    
            var periodendParameter = periodend.HasValue ?
                new ObjectParameter("Periodend", periodend) :
                new ObjectParameter("Periodend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("THAS_CONNECT_GetShortageReportSOSchedule", periodstartParameter, periodendParameter);
        }
    }
}
