//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetail
    {
        public int SalesOrderDetailsID { get; set; }
        public string SalesOrderNumber { get; set; }
        public short LineNumber { get; set; }
        public int PartID { get; set; }
        public Nullable<int> DespatchID { get; set; }
        public short DespatchStatusID { get; set; }
        public System.DateTime DespatchDate { get; set; }
        public Nullable<System.DateTime> ActualDespatchDate { get; set; }
        public decimal QuantityOrdered { get; set; }
        public decimal QuantityDespatched { get; set; }
        public Nullable<int> DeliveryAddressID { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> PartCustomerCrossReferenceID { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string BatchCardNotes { get; set; }
        public string DeliveryNoteText { get; set; }
        public Nullable<int> NominalID { get; set; }
        public Nullable<int> TaxID { get; set; }
        public string QuoteNumber { get; set; }
        public bool OnHold { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CustRequiredDate { get; set; }
        public Nullable<int> QuoteLineNumber { get; set; }
        public decimal StandardCostInBase { get; set; }
        public decimal StandardCostTotal { get; set; }
        public bool PrintedInSalesPickList { get; set; }
        public decimal AdvanceInvoiceValue { get; set; }
        public decimal AssessableValue { get; set; }
        public Nullable<int> ITRTaxStructureID { get; set; }
        public Nullable<System.DateTime> MemoDate2 { get; set; }
        public Nullable<System.DateTime> MemoDate3 { get; set; }
        public Nullable<int> ReferencePartID { get; set; }
        public Nullable<short> OriginalLineNumber { get; set; }
        public Nullable<bool> IsSplitted { get; set; }
        public Nullable<bool> ShowSplittedLineOnReport { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<decimal> Order { get; set; }
        public string UnitPriceSource { get; set; }
        public decimal InitialCost { get; set; }
        public Nullable<System.DateTime> InitialCostDate { get; set; }
        public decimal InitialMark_UpPercent { get; set; }
        public decimal InitialMarginPercent { get; set; }
        public decimal CurrentCost { get; set; }
        public Nullable<System.DateTime> CurrentCostDate { get; set; }
        public decimal CurrentMark_UpPercent { get; set; }
        public decimal CurrentMarginPercent { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
