//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder()
        {
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
        }
    
        public string SalesOrderNumber { get; set; }
        public short SalesOrderStatusCode { get; set; }
        public string SecondSalesReference { get; set; }
        public int CustomerID { get; set; }
        public int DeliveryAddressID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public bool CertificateOfConformity { get; set; }
        public Nullable<int> NominalID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string SalesHeaderText { get; set; }
        public string SalesFooterText { get; set; }
        public Nullable<int> ClockNumber { get; set; }
        public Nullable<System.DateTime> DateRaised { get; set; }
        public short Printed { get; set; }
        public bool Spooled { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<int> IntrastatsDeliveryID { get; set; }
        public Nullable<int> IntrastatsTransactionID { get; set; }
        public Nullable<int> IntrastatsTransportID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public short Status { get; set; }
        public Nullable<bool> ShowPartAllocation { get; set; }
        public string Memo1 { get; set; }
        public string Memo2 { get; set; }
        public string Memo3 { get; set; }
        public string Memo4 { get; set; }
        public string Memo5 { get; set; }
        public string Memo6 { get; set; }
        public string SalesOrderTitle { get; set; }
        public string IssueNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> Days { get; set; }
        public int ServiceStatusID { get; set; }
        public Nullable<int> OrderProjectTypeID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int InvoiceAddressID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
    }
}
